### ISSUE TITLE
Error being thrown each time

### ISSUE THREAD

**Issue by ThomasGreiner** [cgutierrez/JsMinifier#15]
I'm getting the following exception each time I try to minify some JavaScript:

```
Exception in thread Thread-5:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File "./compilers/basecall.py", line 23, in run
  File "./compilers/googleclosurecall.py", line 21, in exec_request
NameError: global name 're' is not defined

error: There was an error minifying the Javascript.
Traceback (most recent call last):
  File "./Minify.py", line 77, in <lambda>
  File "./Minify.py", line 63, in handle_threads
  File "./Minify.py", line 144, in handle_result
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

Looks like there's an `import re` missing in _googleclosurecall.py_ and _uglifycall.py_ but it seems to work for most people so that's quite odd.

**Comment by JosephLeedy** [comment]
I'm getting the same error FWIW. Adding `import re` to the beginning of _googleclosurecall.py_ did fix the issue for me after I restarted Sublime Text.

**Comment by cgutierrez** [comment]
Added the imports. thanks guys!

**Comment by JosephLeedy** [comment]
Thanks Chris!
