### ISSUE TITLE
AttributeError: 'URLError' object has no attribute 'code'

### ISSUE THREAD

**Issue by thegeek** [cgutierrez/JsMinifier#9]
My version is the git one (3/02/12 update).

Exception in thread Thread-13:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 522, in __bootstrap_inner
    self.run()
  File "./compilers/basecall.py", line 26, in run
AttributeError: 'URLError' object has no attribute 'code'

code to minify:

;(function($){
    console.log('prova');
})(jQuery);

**Comment by cgutierrez** [comment]
Thanks for reporting this. You were actually seeing this error as a result of a different error. An error popup should now be displayed with the exact error message. If you see the error again, it's more than likely due to not being able to hit the API of the minifier.
